#!/bin/bash
users=$(gentent passwd |awk -F: '{ print $1 ":" $6}')
sorted_users=$(echo "$users" | sort -t: -k1)
echo "User\tHome Directory"
echo "$sorted_users" |while IFS=: read -r username home_directory; do printf "%s\t%s\n" "$username" "$home_directory"
